const sample_chat = [
  {
    "prompt": "what is python",
    "answer": "Python is a **high-level**, general-purpose programming language that can be used for a wide variety of applications. Here are some key points about Python: \n\n - Interpreted Language \n\n - python is an interpreted language, which means it doesn't need to be compiled before execution. This makes the development process quick and flexible. \n\n - Easy to Learn - Python has a very simple and elegant syntax that is easy for beginners to learn and yet powerful enough for experienced programmers. \n- Cross - platform - Python code can run on various operating systems like Windows, Linux and macOS.This makes Python portable across platforms. \n - Open Source - Python is open source software maintained by the non \n\n - profit Python Software Foundation.It's free to use and distribute. \n\n - Object Oriented - Python supports object \n\n - oriented programming which allows code reuse and modular programming.\n\n - Extensive Libraries - Python has a huge collection of standard and external libraries and frameworks like NumPy, Pandas, Django, Flask etc.This makes nearly every task achievable in Python. \n\n- High - level Language \n\n- Python abstracts away low - level details like memory management.This allows developers to focus on core functionality rather than nitty \n\n- gritty details. \n\n- Dynamic Typing - Variables in Python don't require explicit declaration. The type is resolved at runtime which makes Python very flexible. In summary, Python is a versatile, easy to learn and powerful programming language used for web development, data analysis, AI, machine learning and much more.Its simple syntax, dynamic typing and extensive libraries allow rapid development of robust applications."
  },
  {
    "prompt": "how to learn python?",
    "answer": " Here are some effective ways to learn Python:\n\n - Take an interactive Python course or tutorial.Codecademy, DataCamp, and SoloLearn have great hands- on beginner Python courses.\n\n - Go through the official Python documentation and user guide.The tutorials cover the core language and standard library.\n\n - Practice Python coding exercises on sites like HackerRank, LeetCode, and CodeWars to improve your skills.Start basic and move up to harder challenges.\n\n - Build your own projects.Start small and create things like a calculator, mad libs game, or text - based adventure.Then build up to more complex programs.\n\n - Read Python books like Automate the Boring Stuff, Python Crash Course, or Head - First Python.These will teach fundamentals and popular libraries.\n\n - Watch Python YouTube tutorial playlists.Corey Schafer, CS Dojo, and Mike Dane have great content for beginners.\n\n - Contribute to open source Python projects on GitHub.Reading and improving code is a great way to advance.\n\n - Explore Python web frameworks like Django and Flask to build web apps and sites.\n\n  - Learn Python data analysis libraries like Pandas, NumPy, Matplotlib, and Seaborn.\n\n  - Build a portfolio of Python projects to showcase your skills on GitHub.\n\n  The key is to practice Python coding regularly.Learn the basics then apply your knowledge by building projects.Be curious, persistent, and don't afraid to experiment as you code."
  },
  {
    "prompt": "give me a sample python code",
    "answer": 'Here is a simple Python code sample that prints "Hello World!":\n\n \`\`\`python \n\n # This is a comment \n\n print("Hello World!")\n\n # Print function prints the text in quotes\n\n name = "John" # String variable\n\n age = 25 # Numeric variable\n\n print("My name is", name, "and I am", age, "years old.")\n\n # Strings can be concatenated with +\n\n print("Hello " + name + ", nice to meet you!")\n\n # Asking user to input their name\n\n # Indentation is important in Python\n\n else:\n\n print(name, "is under 18.")\n\n # For loop\n\n for x in range(5):\n\n print(x)\n\n # Imports math module\n\n import math\n\n print("Square root of 16 is", math.sqrt(16))\n\n \`\`\`\n\n This covers:\n\n - Comments\n\n - Print function\n\n - Variables\n\n - String concatenation\n\n - User input\n\n - If /else statements\n\n - For loops\n\n - Importing modules\n\n This is just a basic intro, but it shows the core concepts and syntax of Python programming.Play around with the code example to understand it better.\n\n'
  }]

export default sample_chat
